-- =====================================================================
--  identity-access: refresh tokens (SEC-02, security test S-44)
--
--  Access tokens stay short-lived (15 minutes). A refresh token keeps a user
--  signed in without re-entering a password, and is rotated on every use.
--  Only a SHA-256 hash is stored: a copy of this table cannot sign anyone in.
--
--  All tokens descending from one sign-in share a family. Presenting a token
--  that was already rotated means it was copied, so the whole family is
--  revoked and the user must sign in again.
-- =====================================================================

CREATE TABLE refresh_token (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    token_hash        VARCHAR(64)  NOT NULL,
    family_id         VARCHAR(36)  NOT NULL,
    family_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    issued_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at        TIMESTAMP WITH TIME ZONE,
    revoked_reason    VARCHAR(32),
    replaced_by_id    BIGINT,
    created_by_ip     VARCHAR(45),
    user_agent        VARCHAR(255),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        VARCHAR(160),
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        VARCHAR(160),
    version           BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT ck_refresh_token_reason CHECK (revoked_reason IS NULL OR revoked_reason IN
        ('ROTATED', 'SIGNED_OUT', 'REUSE_DETECTED', 'ACCOUNT_SUSPENDED', 'PASSWORD_RESET'))
);

CREATE INDEX ix_refresh_token_family ON refresh_token (family_id);
CREATE INDEX ix_refresh_token_user   ON refresh_token (user_id, revoked_at);
CREATE INDEX ix_refresh_token_expiry ON refresh_token (expires_at);
