-- =====================================================================
--  identity-access: invitation and password-reset links (IAM-08, IAM-11)
--
--  A new user is invited by email and sets their own password; nobody else
--  ever knows it. A forgotten password is replaced the same way. Each link is
--  single-use and short-lived, and only a SHA-256 hash of it is stored.
-- =====================================================================

CREATE TABLE user_token (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT      NOT NULL,
    purpose            VARCHAR(24) NOT NULL,
    token_hash         VARCHAR(64) NOT NULL,
    expires_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at            TIMESTAMP WITH TIME ZONE,
    revoked_at         TIMESTAMP WITH TIME ZONE,
    created_by_user_id BIGINT,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by         VARCHAR(160),
    updated_at         TIMESTAMP WITH TIME ZONE,
    updated_by         VARCHAR(160),
    version            BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT uk_user_token_hash    UNIQUE (token_hash),
    CONSTRAINT fk_user_token_user    FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_user_token_creator FOREIGN KEY (created_by_user_id) REFERENCES app_user (id),
    CONSTRAINT ck_user_token_purpose CHECK (purpose IN ('INVITATION', 'PASSWORD_RESET'))
);

CREATE INDEX ix_user_token_user ON user_token (user_id, purpose);
