-- =====================================================================
--  identity-access: users, roles, vessel assignment
-- =====================================================================

CREATE TABLE app_user (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR(254) NOT NULL,
    password_hash      VARCHAR(72)  NOT NULL,
    full_name          VARCHAR(160) NOT NULL,
    role               VARCHAR(32)  NOT NULL,
    organization_id    BIGINT,
    status             VARCHAR(16)  NOT NULL,
    last_login_at      TIMESTAMP WITH TIME ZONE,
    failed_login_count INTEGER      NOT NULL DEFAULT 0,
    locked_until       TIMESTAMP WITH TIME ZONE,
    seed_marker        VARCHAR(8),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by         VARCHAR(160),
    updated_at         TIMESTAMP WITH TIME ZONE,
    updated_by         VARCHAR(160),
    version            BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uk_app_user_email UNIQUE (email),
    CONSTRAINT fk_app_user_organization FOREIGN KEY (organization_id) REFERENCES organization (id),

    -- A Platform Admin belongs to no organization; everybody else must belong
    -- to exactly one. Enforced here so no code path can create an unscoped
    -- tenant user, whatever the service layer does.
    CONSTRAINT ck_app_user_org_scope CHECK (
        (role = 'PLATFORM_ADMIN' AND organization_id IS NULL)
        OR (role <> 'PLATFORM_ADMIN' AND organization_id IS NOT NULL)
    ),

    CONSTRAINT ck_app_user_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'INVITED'))
);

CREATE INDEX ix_app_user_org_role ON app_user (organization_id, role);
CREATE INDEX ix_app_user_role     ON app_user (role);

CREATE TABLE user_vessel_assignment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    vessel_id           BIGINT NOT NULL,
    assigned_by_user_id BIGINT,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by          VARCHAR(160),
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          VARCHAR(160),
    version             BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_user_vessel UNIQUE (user_id, vessel_id),
    CONSTRAINT fk_uva_user   FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_uva_vessel FOREIGN KEY (vessel_id) REFERENCES vessel (id),
    CONSTRAINT fk_uva_assigner FOREIGN KEY (assigned_by_user_id) REFERENCES app_user (id)
);

CREATE INDEX ix_uva_user   ON user_vessel_assignment (user_id);
CREATE INDEX ix_uva_vessel ON user_vessel_assignment (vessel_id);
