-- =====================================================================
--  OI-16: Seastella-side users are scoped to a SET of client organizations.
--
--  SoW section 5 labels the role "Service Coordinator (Seastella)" - the only
--  role carrying that parenthetical - and gives its access scope as "Assigned
--  service scope" rather than "own organization". Section 2 has Seastella
--  serving "ship-management companies" (plural) and section 4.1 defines an
--  Organization as "the client company". A Coordinator is therefore platform
--  staff assigned to several clients, not a member of one.
--
--  The Service Engineer is platform-side for the same reason (SoW section 5
--  maps it to "Service Provider / Technician", an external vendor), but needs
--  no organization assignment at all: the job remains its lowest-level
--  assignment boundary.
-- =====================================================================

CREATE TABLE user_organization_assignment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    organization_id     BIGINT NOT NULL,
    assigned_by_user_id BIGINT,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by          VARCHAR(160),
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          VARCHAR(160),
    version             BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_user_organization UNIQUE (user_id, organization_id),
    CONSTRAINT fk_uoa_user         FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_uoa_organization FOREIGN KEY (organization_id) REFERENCES organization (id),
    CONSTRAINT fk_uoa_assigner     FOREIGN KEY (assigned_by_user_id) REFERENCES app_user (id)
);

CREATE INDEX ix_uoa_user         ON user_organization_assignment (user_id);
CREATE INDEX ix_uoa_organization ON user_organization_assignment (organization_id);

-- Platform-side roles hold no organization_id; client-tenant roles must.
-- Replaces the earlier PLATFORM_ADMIN-only rule from V3.
ALTER TABLE app_user DROP CONSTRAINT ck_app_user_org_scope;

ALTER TABLE app_user ADD CONSTRAINT ck_app_user_org_scope CHECK (
    (role IN ('PLATFORM_ADMIN', 'SERVICE_COORDINATOR', 'SERVICE_ENGINEER')
         AND organization_id IS NULL)
    OR (role NOT IN ('PLATFORM_ADMIN', 'SERVICE_COORDINATOR', 'SERVICE_ENGINEER')
         AND organization_id IS NOT NULL)
);

-- Forward migration for any existing deployment: a Coordinator previously
-- pinned to one organization keeps exactly that organization as its first
-- assignment, so no access is gained or lost by this change.
INSERT INTO user_organization_assignment
    (user_id, organization_id, assigned_by_user_id, created_at, version)
SELECT u.id, u.organization_id, NULL, CURRENT_TIMESTAMP, 0
FROM app_user u
WHERE u.role = 'SERVICE_COORDINATOR'
  AND u.organization_id IS NOT NULL;

UPDATE app_user SET organization_id = NULL
WHERE role IN ('SERVICE_COORDINATOR', 'SERVICE_ENGINEER');
