-- =====================================================================
--  service-request: the engineer's job log
--
--  Between "start work" and the completion report the job had no record:
--  when the engineer got aboard, what was done and when, where it waited
--  on parts. The job log keeps that, entry by entry, each with the time it
--  happened (which may be entered a little after the fact) and, where it
--  helps, a photograph stored as a document on the request.
-- =====================================================================

CREATE TABLE job_log_entry (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id BIGINT        NOT NULL,
    vessel_id          BIGINT        NOT NULL,
    author_user_id     BIGINT        NOT NULL,
    kind               VARCHAR(16)   NOT NULL,
    occurred_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    note               VARCHAR(2000),
    document_id        BIGINT,
    automatic          BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by         VARCHAR(160),
    updated_at         TIMESTAMP WITH TIME ZONE,
    updated_by         VARCHAR(160),
    version            BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT fk_job_log_request FOREIGN KEY (service_request_id, vessel_id)
        REFERENCES service_request (id, vessel_id),
    CONSTRAINT fk_job_log_author FOREIGN KEY (author_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_job_log_document FOREIGN KEY (document_id) REFERENCES document (id),
    CONSTRAINT ck_job_log_kind CHECK (kind IN
        ('ARRIVED', 'STARTED', 'UPDATE', 'WAITING', 'RESUMED', 'FINISHED', 'LEFT', 'REPORTED'))
);

CREATE INDEX ix_job_log_request ON job_log_entry (service_request_id, occurred_at);
