-- =====================================================================
--  service-request: the request aggregate, its transition log, completion
-- =====================================================================

CREATE TABLE problem_type (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_category_id BIGINT       NOT NULL,
    code                  VARCHAR(60)  NOT NULL,
    label                 VARCHAR(160) NOT NULL,
    display_order         INTEGER      NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by            VARCHAR(160),
    updated_at            TIMESTAMP WITH TIME ZONE,
    updated_by            VARCHAR(160),
    version               BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_problem_type_code UNIQUE (code),
    CONSTRAINT fk_problem_type_category FOREIGN KEY (equipment_category_id)
        REFERENCES equipment_category (id)
);

CREATE INDEX ix_problem_type_category ON problem_type (equipment_category_id, display_order);

CREATE TABLE service_request (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number                  VARCHAR(40)   NOT NULL,
    organization_id                 BIGINT        NOT NULL,
    vessel_id                       BIGINT        NOT NULL,
    spare_id                        BIGINT        NOT NULL,
    problem_type_id                 BIGINT,
    raised_by_user_id               BIGINT        NOT NULL,
    title                           VARCHAR(200)  NOT NULL,
    description                     VARCHAR(4000) NOT NULL,
    priority                        VARCHAR(16)   NOT NULL,
    status                          VARCHAR(40)   NOT NULL,
    operational_approved_by_user_id BIGINT,
    operational_approved_at         TIMESTAMP WITH TIME ZONE,
    assigned_engineer_user_id       BIGINT,
    assigned_by_user_id             BIGINT,
    assigned_at                     TIMESTAMP WITH TIME ZONE,
    resolution_type                 VARCHAR(24)   NOT NULL,
    last_reason                     VARCHAR(2000),
    closed_at                       TIMESTAMP WITH TIME ZONE,
    closed_by_user_id               BIGINT,
    seed_marker                     VARCHAR(8),
    created_at                      TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by                      VARCHAR(160),
    updated_at                      TIMESTAMP WITH TIME ZONE,
    updated_by                      VARCHAR(160),
    version                         BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT uk_service_request_number UNIQUE (request_number),

    -- vessel_id is denormalised from the spare so the scope predicate is a
    -- single-table filter. The composite FK is what keeps the two consistent:
    -- the spare must belong to the vessel the request claims.
    CONSTRAINT fk_sr_spare FOREIGN KEY (spare_id, vessel_id) REFERENCES spare (id, vessel_id),
    CONSTRAINT fk_sr_vessel_org FOREIGN KEY (vessel_id, organization_id)
        REFERENCES vessel (id, organization_id),
    CONSTRAINT fk_sr_problem_type FOREIGN KEY (problem_type_id) REFERENCES problem_type (id),
    CONSTRAINT fk_sr_raised_by FOREIGN KEY (raised_by_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_sr_engineer FOREIGN KEY (assigned_engineer_user_id) REFERENCES app_user (id),

    -- Lets the invoice table pin itself to the same vessel.
    CONSTRAINT uk_sr_id_vessel UNIQUE (id, vessel_id),

    CONSTRAINT ck_sr_priority CHECK (priority IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')),

    -- An assigned request must record who assigned it and when: assignment is
    -- the step the invoice gate protects, so it is never left half-recorded.
    CONSTRAINT ck_sr_assignment_complete CHECK (
        assigned_engineer_user_id IS NULL
        OR (assigned_by_user_id IS NOT NULL AND assigned_at IS NOT NULL)
    )
);

-- Dashboard queues: "open requests for my vessels, by status".
CREATE INDEX ix_sr_vessel_status   ON service_request (vessel_id, status);
CREATE INDEX ix_sr_org_status      ON service_request (organization_id, status);
CREATE INDEX ix_sr_status          ON service_request (status);
CREATE INDEX ix_sr_engineer        ON service_request (assigned_engineer_user_id, status);
CREATE INDEX ix_sr_spare           ON service_request (spare_id);
CREATE INDEX ix_sr_vessel_created  ON service_request (vessel_id, created_at DESC);
CREATE INDEX ix_sr_open            ON service_request (vessel_id, closed_at);

-- Append-only history of the state machine itself.
CREATE TABLE service_request_transition (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id BIGINT      NOT NULL,
    vessel_id          BIGINT      NOT NULL,
    from_status        VARCHAR(40),
    to_status          VARCHAR(40) NOT NULL,
    action             VARCHAR(40) NOT NULL,
    actor_user_id      BIGINT,
    actor_role         VARCHAR(32),
    reason             VARCHAR(2000),
    occurred_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_srt_request FOREIGN KEY (service_request_id) REFERENCES service_request (id)
);

CREATE INDEX ix_srt_request  ON service_request_transition (service_request_id, occurred_at);
CREATE INDEX ix_srt_vessel   ON service_request_transition (vessel_id, occurred_at DESC);

CREATE TABLE completion_report (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id       BIGINT        NOT NULL,
    vessel_id                BIGINT        NOT NULL,
    engineer_user_id         BIGINT        NOT NULL,
    work_performed           VARCHAR(4000) NOT NULL,
    parts_used               VARCHAR(2000),
    outcome                  VARCHAR(400)  NOT NULL,
    final_cost               NUMERIC(14,2),
    service_date             DATE,
    running_hours_at_service NUMERIC(12,2),
    reported_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    reconciled_at            TIMESTAMP WITH TIME ZONE,
    cost_variance            NUMERIC(14,2),
    relay_note               VARCHAR(2000),
    seed_marker              VARCHAR(8),
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by               VARCHAR(160),
    updated_at               TIMESTAMP WITH TIME ZONE,
    updated_by               VARCHAR(160),
    version                  BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT uk_completion_request UNIQUE (service_request_id),
    CONSTRAINT fk_cr_request  FOREIGN KEY (service_request_id, vessel_id)
        REFERENCES service_request (id, vessel_id),
    CONSTRAINT fk_cr_engineer FOREIGN KEY (engineer_user_id) REFERENCES app_user (id)
);

CREATE INDEX ix_cr_engineer ON completion_report (engineer_user_id, reported_at DESC);
CREATE INDEX ix_cr_vessel   ON completion_report (vessel_id);
