-- =====================================================================
--  masterdata-import: VMP spreadsheet upload, preview, commit (SoW s10)
--
--  An upload never touches fleet data. Every row is staged here with what it
--  would do - add, change, leave alone, or refuse - and the change is applied
--  only when an administrator, having seen that preview, confirms it (IMP-08,
--  IMP-09, security test S-37). The staged rows stay afterwards: they are the
--  record of what an import did, with the before and after of every field.
-- =====================================================================

CREATE TABLE import_batch (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name             VARCHAR(255) NOT NULL,
    file_size             BIGINT       NOT NULL,
    status                VARCHAR(16)  NOT NULL,
    uploaded_by_user_id   BIGINT       NOT NULL,
    uploaded_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    -- G8: a commit is refused unless the same person has seen the preview.
    previewed_by_user_id  BIGINT,
    previewed_at          TIMESTAMP WITH TIME ZONE,
    committed_by_user_id  BIGINT,
    committed_at          TIMESTAMP WITH TIME ZONE,
    discarded_at          TIMESTAMP WITH TIME ZONE,
    row_count             INTEGER      NOT NULL,
    new_count             INTEGER      NOT NULL,
    modified_count        INTEGER      NOT NULL,
    unchanged_count       INTEGER      NOT NULL,
    invalid_count         INTEGER      NOT NULL,
    duplicate_count       INTEGER      NOT NULL,
    applied_count         INTEGER,
    -- Which vessels the file touched, for the history list.
    vessels_summary       VARCHAR(500),
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by            VARCHAR(160),
    updated_at            TIMESTAMP WITH TIME ZONE,
    updated_by            VARCHAR(160),
    version               BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_import_batch_uploader  FOREIGN KEY (uploaded_by_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_import_batch_previewer FOREIGN KEY (previewed_by_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_import_batch_committer FOREIGN KEY (committed_by_user_id) REFERENCES app_user (id),
    CONSTRAINT ck_import_batch_status CHECK (status IN ('PREVIEW', 'COMMITTED', 'DISCARDED'))
);

CREATE INDEX ix_import_batch_recent ON import_batch (id DESC);
CREATE INDEX ix_import_batch_uploader ON import_batch (uploaded_by_user_id, id);

CREATE TABLE import_row (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id     BIGINT       NOT NULL,
    -- The row number in the sheet, so a message points at what the person sees.
    row_number   INTEGER      NOT NULL,
    imo_number   VARCHAR(16),
    vmp_ref      VARCHAR(32),
    spare_name   VARCHAR(200),
    vessel_id    BIGINT,
    spare_id     BIGINT,
    outcome      VARCHAR(16)  NOT NULL,
    messages     VARCHAR(1000),
    values_json  VARCHAR(4000) NOT NULL,
    changes_json VARCHAR(4000),
    applied      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by   VARCHAR(160),
    updated_at   TIMESTAMP WITH TIME ZONE,
    updated_by   VARCHAR(160),
    version      BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_import_row_batch FOREIGN KEY (batch_id) REFERENCES import_batch (id),
    CONSTRAINT ck_import_row_outcome CHECK (
        outcome IN ('NEW', 'MODIFIED', 'UNCHANGED', 'INVALID', 'DUPLICATE'))
);

CREATE INDEX ix_import_row_batch ON import_row (batch_id, row_number);
