-- =====================================================================
--  notification: in-app alerts, email delivery, configurable recipients
--
--  SoW s7 "Notifications: in-app and email alerts for requests, troubleshooting
--  outcomes, live-chat escalation, invoices, approvals, assignment and
--  completion"; s11 names who hears about what. Recipients are rows in
--  notification_rule, not code (SOURCE-B s35, OI-03), so a client answer to
--  "who should be told" is a data change.
-- =====================================================================

CREATE TABLE notification (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id BIGINT       NOT NULL,
    event_type        VARCHAR(48)  NOT NULL,
    category          VARCHAR(16)  NOT NULL,
    title             VARCHAR(200) NOT NULL,
    body              VARCHAR(2000),
    entity_type       VARCHAR(48),
    entity_id         BIGINT,
    organization_id   BIGINT,
    vessel_id         BIGINT,
    -- Maintenance alerts only: the colour band being announced.
    due_status        VARCHAR(24),
    in_app            BOOLEAN      NOT NULL,
    read_at           TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        VARCHAR(160),
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        VARCHAR(160),
    version           BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_notification_recipient FOREIGN KEY (recipient_user_id) REFERENCES app_user (id),
    CONSTRAINT ck_notification_category CHECK (category IN ('ACTION', 'UPDATE', 'MAINTENANCE'))
);

-- The bell reads "my newest" and "how many unread", nothing else.
CREATE INDEX ix_notification_inbox  ON notification (recipient_user_id, created_at);
CREATE INDEX ix_notification_unread ON notification (recipient_user_id, read_at);

CREATE TABLE notification_delivery (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT       NOT NULL,
    channel         VARCHAR(16)  NOT NULL,
    address         VARCHAR(254) NOT NULL,
    status          VARCHAR(16)  NOT NULL,
    attempts        INTEGER      NOT NULL DEFAULT 0,
    last_error      VARCHAR(500),
    sent_at         TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by      VARCHAR(160),
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      VARCHAR(160),
    version         BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_delivery_notification FOREIGN KEY (notification_id) REFERENCES notification (id),
    CONSTRAINT ck_delivery_channel CHECK (channel IN ('EMAIL')),
    -- SKIPPED: no mail server configured, so nothing was attempted.
    CONSTRAINT ck_delivery_status CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'SKIPPED'))
);

CREATE INDEX ix_delivery_status ON notification_delivery (status, id);
CREATE INDEX ix_delivery_notification ON notification_delivery (notification_id);

CREATE TABLE notification_rule (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type     VARCHAR(48) NOT NULL,
    recipient_role VARCHAR(32) NOT NULL,
    in_app         BOOLEAN     NOT NULL,
    email          BOOLEAN     NOT NULL,
    active         BOOLEAN     NOT NULL,
    source_ref     VARCHAR(80),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by     VARCHAR(160),
    updated_at     TIMESTAMP WITH TIME ZONE,
    updated_by     VARCHAR(160),
    version        BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT uk_notification_rule UNIQUE (event_type, recipient_role),
    CONSTRAINT ck_rule_recipient_role CHECK (recipient_role IN (
        'PLATFORM_ADMIN', 'TECHNICAL_HEAD', 'SHIP_MANAGER', 'CAPTAIN',
        'SERVICE_COORDINATOR', 'SERVICE_ENGINEER'))
);

-- The SoW s11 matrix. Event types are the workflow's own action names, plus
-- MAINTENANCE_DUE for colour-status changes. Platform Admin has no rows: per
-- s11 and OI-12 the platform-wide activity feed is its channel, and a row can
-- be added if Seastella asks for individual alerts too.
INSERT INTO notification_rule (event_type, recipient_role, in_app, email, active, source_ref, created_at, version) VALUES
    ('RAISE',                  'SHIP_MANAGER',        TRUE, TRUE, TRUE, 'SoW 11: request raised',                CURRENT_TIMESTAMP, 0),
    ('SUBMIT_FOR_APPROVAL',    'SHIP_MANAGER',        TRUE, TRUE, TRUE, 'SoW 6.1: Ship Manager reviews',         CURRENT_TIMESTAMP, 0),
    ('SUBMIT_FOR_APPROVAL',    'SERVICE_COORDINATOR', TRUE, TRUE, TRUE, 'SoW 11: troubleshooting unresolved',    CURRENT_TIMESTAMP, 0),
    ('RESUBMIT',               'SHIP_MANAGER',        TRUE, TRUE, TRUE, 'SoW 6.1: clarification loop',           CURRENT_TIMESTAMP, 0),
    ('ESCALATE_TO_LIVE_AGENT', 'SERVICE_COORDINATOR', TRUE, TRUE, TRUE, 'SoW 11: live agent escalation',         CURRENT_TIMESTAMP, 0),
    ('APPROVE_OPERATIONAL',    'CAPTAIN',             TRUE, TRUE, TRUE, 'SoW 11: request approved',              CURRENT_TIMESTAMP, 0),
    ('APPROVE_OPERATIONAL',    'SERVICE_COORDINATOR', TRUE, TRUE, TRUE, 'SoW 6.1: forwarded to Coordinator',     CURRENT_TIMESTAMP, 0),
    ('REJECT',                 'CAPTAIN',             TRUE, TRUE, TRUE, 'SoW 11: request rejected',              CURRENT_TIMESTAMP, 0),
    ('REQUEST_CLARIFICATION',  'CAPTAIN',             TRUE, TRUE, TRUE, 'SoW 11: clarification requested',       CURRENT_TIMESTAMP, 0),
    ('CLOSE_NO_COST',          'CAPTAIN',             TRUE, TRUE, TRUE, 'SoW 8.3: request status',               CURRENT_TIMESTAMP, 0),
    ('CLOSE_NO_COST',          'SHIP_MANAGER',        TRUE, TRUE, TRUE, 'SoW 8.2: request status',               CURRENT_TIMESTAMP, 0),
    ('RAISE_INVOICE',          'SHIP_MANAGER',        TRUE, TRUE, TRUE, 'SoW 11: invoice raised',                CURRENT_TIMESTAMP, 0),
    ('ACCEPT_INVOICE',         'SERVICE_COORDINATOR', TRUE, TRUE, TRUE, 'SoW 11: invoice accepted',              CURRENT_TIMESTAMP, 0),
    ('ACCEPT_INVOICE',         'CAPTAIN',             TRUE, TRUE, TRUE, 'SoW 8.3: invoice accepted',             CURRENT_TIMESTAMP, 0),
    ('REJECT_INVOICE',         'SERVICE_COORDINATOR', TRUE, TRUE, TRUE, 'SoW 11: invoice rejected',              CURRENT_TIMESTAMP, 0),
    ('QUERY_INVOICE',          'SERVICE_COORDINATOR', TRUE, TRUE, TRUE, 'SoW 11: invoice queried',               CURRENT_TIMESTAMP, 0),
    ('ASSIGN_ENGINEER',        'SERVICE_ENGINEER',    TRUE, TRUE, TRUE, 'SoW 11: forwarded to engineer',         CURRENT_TIMESTAMP, 0),
    ('SUBMIT_COMPLETION',      'SERVICE_COORDINATOR', TRUE, TRUE, TRUE, 'SoW 11: completion report (only)',      CURRENT_TIMESTAMP, 0),
    ('COMPLETE',               'SHIP_MANAGER',        TRUE, TRUE, TRUE, 'SoW 11: Coordinator marks completed',   CURRENT_TIMESTAMP, 0),
    ('COMPLETE',               'CAPTAIN',             TRUE, TRUE, TRUE, 'SoW 8.3: service completed',            CURRENT_TIMESTAMP, 0),
    ('MAINTENANCE_DUE',        'CAPTAIN',             TRUE, TRUE, TRUE, 'SoW 11: maintenance status change',     CURRENT_TIMESTAMP, 0),
    ('MAINTENANCE_DUE',        'SHIP_MANAGER',        TRUE, TRUE, TRUE, 'SoW 11: maintenance status change',     CURRENT_TIMESTAMP, 0),
    ('MAINTENANCE_DUE',        'TECHNICAL_HEAD',      TRUE, TRUE, TRUE, 'SoW 11: maintenance status change',     CURRENT_TIMESTAMP, 0);
