-- =====================================================================
--  notification: certificate expiry reminders (SoW s7, s11; NOT-11, MNT-13)
--
--  "Reminders before a certificate expires." A reminder is sent once per
--  threshold - 90 days out, 30, 7, and on the day it lapses - so the same
--  certificate does not alert every night for three months. The last threshold
--  announced is remembered here, exactly as spare_due_state remembers the last
--  colour band announced.
-- =====================================================================

CREATE TABLE certificate_alert_state (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id         BIGINT      NOT NULL,
    last_threshold_days INTEGER     NOT NULL,
    expiry_date         DATE        NOT NULL,
    alerted_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by          VARCHAR(160),
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          VARCHAR(160),
    version             BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT uk_certificate_alert_document UNIQUE (document_id),
    CONSTRAINT fk_certificate_alert_document FOREIGN KEY (document_id) REFERENCES document (id)
);

-- Who hears about an expiring certificate (SoW s11 shape: the vessel's people
-- and the organization's Technical Head).
INSERT INTO notification_rule (event_type, recipient_role, in_app, email, active, source_ref, created_at, version)
VALUES
    ('CERTIFICATE_EXPIRING', 'CAPTAIN',        TRUE, TRUE, TRUE, 'SoW 7: certificate expiry reminder', CURRENT_TIMESTAMP, 0),
    ('CERTIFICATE_EXPIRING', 'SHIP_MANAGER',   TRUE, TRUE, TRUE, 'SoW 7: certificate expiry reminder', CURRENT_TIMESTAMP, 0),
    ('CERTIFICATE_EXPIRING', 'TECHNICAL_HEAD', TRUE, TRUE, TRUE, 'SoW 7: certificate expiry reminder', CURRENT_TIMESTAMP, 0);
