-- =====================================================================
--  notification: reminders before a piece of equipment expires
--
--  Equipment carries an expiry date of its own (spare.expiration_date): the
--  day the unit stops being fit for use, whatever its service history says -
--  a life-limited battery, a hydrostatic release, a liferaft bottle. Until
--  now nothing watched it. It was shown on the equipment record, in plain
--  text, and whoever opened that record was the only person who knew.
--
--  The client asked for the same two notices they asked for on maintenance:
--  one at 60 days, one at 15. So the same shape as certificate_alert_state -
--  remember the last threshold announced for a unit, and announce again only
--  when a tighter one is crossed, or when somebody changes the date.
--
--  Sixty and fifteen are configuration, not code
--  (seastella.notification.equipment.warning-days), and they default to the
--  same ladder the colour bands use, so what a superintendent is emailed and
--  what the equipment list shows them agree.
-- =====================================================================

CREATE TABLE equipment_expiry_alert_state (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spare_id            BIGINT      NOT NULL,
    last_threshold_days INTEGER     NOT NULL,
    expiry_date         DATE        NOT NULL,
    alerted_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by          VARCHAR(160),
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          VARCHAR(160),
    version             BIGINT      NOT NULL DEFAULT 0,

    -- One row per unit: this is a bookmark, not a history. What was sent to
    -- whom is already kept in notification and notification_delivery.
    CONSTRAINT uk_equipment_expiry_alert_spare UNIQUE (spare_id),
    -- Equipment deleted takes its bookmark with it.
    CONSTRAINT fk_equipment_expiry_alert_spare FOREIGN KEY (spare_id)
        REFERENCES spare (id) ON DELETE CASCADE
);

-- Who hears about expiring equipment: the same people as an expiring
-- certificate, because it is the same problem - a unit that may not legally
-- or safely stay in service - reached by a different route.
INSERT INTO notification_rule (event_type, recipient_role, in_app, email, active, source_ref, created_at, version)
VALUES
    ('EQUIPMENT_EXPIRING', 'CAPTAIN',        TRUE, TRUE, TRUE, 'Client: 60/15 day expiry notice', CURRENT_TIMESTAMP, 0),
    ('EQUIPMENT_EXPIRING', 'SHIP_MANAGER',   TRUE, TRUE, TRUE, 'Client: 60/15 day expiry notice', CURRENT_TIMESTAMP, 0),
    ('EQUIPMENT_EXPIRING', 'TECHNICAL_HEAD', TRUE, TRUE, TRUE, 'Client: 60/15 day expiry notice', CURRENT_TIMESTAMP, 0);
