-- =====================================================================
--  notification: tell the vessel when a unit falls behind the master sheet
--
--  The equipment list has shown software currency as a colour since the
--  master sheet arrived, but showing is not telling: a superintendent has to
--  open the vessel to find out. The client asked for an alert per unit, so
--  this is the push behind the colour.
--
--  The gap itself is remembered, not merely the fact that something was said.
--  A unit reported as 5.4 against 5.6 is news again when the sheet moves to
--  5.7, and again when the vessel flashes it to 5.5 and is still behind: each
--  is a different gap. Remembering only "told them" would silence both, and
--  remembering nothing would mail the same forty units every night until
--  somebody filtered the sender.
-- =====================================================================

CREATE TABLE software_alert_state (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spare_id          BIGINT      NOT NULL,
    -- Both sides of the gap that was announced, so a change in either is news.
    installed_version VARCHAR(64) NOT NULL,
    latest_version    VARCHAR(64) NOT NULL,
    alerted_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        VARCHAR(160),
    updated_at        TIMESTAMP WITH TIME ZONE,
    updated_by        VARCHAR(160),
    version           BIGINT      NOT NULL DEFAULT 0,

    -- One row per unit: a bookmark, not a history. What was sent to whom is
    -- already in notification and notification_delivery.
    CONSTRAINT uk_software_alert_spare UNIQUE (spare_id),
    CONSTRAINT fk_software_alert_spare FOREIGN KEY (spare_id)
        REFERENCES spare (id) ON DELETE CASCADE
);

-- The same people an expiring certificate reaches: it is the vessel's problem
-- to act on and the office's to plan for.
INSERT INTO notification_rule (event_type, recipient_role, in_app, email, active, source_ref, created_at, version)
VALUES
    ('SOFTWARE_OUTDATED', 'CAPTAIN',        TRUE, TRUE, TRUE, 'Client: software update due', CURRENT_TIMESTAMP, 0),
    ('SOFTWARE_OUTDATED', 'SHIP_MANAGER',   TRUE, TRUE, TRUE, 'Client: software update due', CURRENT_TIMESTAMP, 0),
    ('SOFTWARE_OUTDATED', 'TECHNICAL_HEAD', TRUE, TRUE, TRUE, 'Client: software update due', CURRENT_TIMESTAMP, 0);
