-- =====================================================================
--  invoice: payment terms and payments received
--
--  V6 left payment out on purpose: settlement - collecting or moving money,
--  a gateway - is out of scope (SoW s6.2, s15) and still is. What is added
--  here is a record, kept by the Coordinator, of money received through
--  Seastella's own finance process: the terms agreed on the invoice (how much
--  in advance, and by when the whole is due) and each payment as it arrives.
--  Nothing here gates the workflow; it tells people where the money stands so
--  they can decide whether work starts or continues.
-- =====================================================================

-- Terms, set by the Coordinator when raising the invoice.
ALTER TABLE invoice ADD COLUMN advance_percent INTEGER NOT NULL DEFAULT 0;
ALTER TABLE invoice ADD CONSTRAINT ck_invoice_advance CHECK (advance_percent BETWEEN 0 AND 100);
ALTER TABLE invoice ADD COLUMN payment_due_date DATE;
-- When the "payment overdue" alert went out, so it is sent once per due date.
ALTER TABLE invoice ADD COLUMN overdue_alerted_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE invoice_payment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          BIGINT        NOT NULL,
    amount              NUMERIC(14,2) NOT NULL,
    received_on         DATE          NOT NULL,
    method              VARCHAR(24)   NOT NULL,
    reference           VARCHAR(120),
    note                VARCHAR(500),
    recorded_by_user_id BIGINT        NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by          VARCHAR(160),
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          VARCHAR(160),
    version             BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT fk_payment_invoice FOREIGN KEY (invoice_id) REFERENCES invoice (id),
    CONSTRAINT fk_payment_recorded_by FOREIGN KEY (recorded_by_user_id) REFERENCES app_user (id),
    CONSTRAINT ck_payment_amount CHECK (amount > 0),
    CONSTRAINT ck_payment_method CHECK (method IN ('BANK_TRANSFER', 'CHEQUE', 'CASH', 'CARD', 'OTHER'))
);

CREATE INDEX ix_invoice_payment_invoice ON invoice_payment (invoice_id);

-- Who is told when a payment passes its due date: the Coordinators serving the
-- organization, who decide whether work continues, and the vessel's Ship
-- Manager, who pays.
INSERT INTO notification_rule (event_type, recipient_role, in_app, email, active, source_ref, created_at, version)
VALUES
    ('INVOICE_PAYMENT_OVERDUE', 'SERVICE_COORDINATOR', TRUE, TRUE, TRUE, 'Payment tracking: balance past due', CURRENT_TIMESTAMP, 0),
    ('INVOICE_PAYMENT_OVERDUE', 'SHIP_MANAGER',        TRUE, TRUE, TRUE, 'Payment tracking: balance past due', CURRENT_TIMESTAMP, 0);
