-- =====================================================================
--  invoice: acceptance and tracking only
--
--  There is deliberately NO paid status, NO payment reference and NO
--  settlement column. SoW s7 classifies payment settlement as Out of Scope
--  and s15 confirms settlement stays with Seastella's existing finance
--  process. Their absence is a recorded decision, not an oversight.
-- =====================================================================

CREATE TABLE invoice (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number        VARCHAR(40)   NOT NULL,
    service_request_id    BIGINT        NOT NULL,
    organization_id       BIGINT        NOT NULL,
    vessel_id             BIGINT        NOT NULL,
    raised_by_user_id     BIGINT        NOT NULL,
    currency              VARCHAR(3)    NOT NULL,
    amount                NUMERIC(14,2) NOT NULL,
    description           VARCHAR(2000) NOT NULL,
    status                VARCHAR(24)   NOT NULL,
    decided_by_user_id    BIGINT,
    decided_at            TIMESTAMP WITH TIME ZONE,
    decision_note         VARCHAR(2000),
    supersedes_invoice_id BIGINT,
    seed_marker           VARCHAR(8),
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by            VARCHAR(160),
    updated_at            TIMESTAMP WITH TIME ZONE,
    updated_by            VARCHAR(160),
    version               BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT uk_invoice_number UNIQUE (invoice_number),
    CONSTRAINT fk_invoice_request FOREIGN KEY (service_request_id, vessel_id)
        REFERENCES service_request (id, vessel_id),
    CONSTRAINT fk_invoice_raised_by FOREIGN KEY (raised_by_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_invoice_decided_by FOREIGN KEY (decided_by_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_invoice_supersedes FOREIGN KEY (supersedes_invoice_id) REFERENCES invoice (id),

    CONSTRAINT ck_invoice_status CHECK (
        status IN ('RAISED', 'ACCEPTED', 'REJECTED', 'QUERIED', 'SUPERSEDED')
    ),
    CONSTRAINT ck_invoice_amount CHECK (amount >= 0),

    -- A decided invoice records who decided it and when. The acceptance is what
    -- opens the engineer-assignment gate, so it must never be attributable to
    -- nobody.
    CONSTRAINT ck_invoice_decision_complete CHECK (
        status IN ('RAISED', 'SUPERSEDED')
        OR (decided_by_user_id IS NOT NULL AND decided_at IS NOT NULL)
    )
);

-- The gate query: "does an ACCEPTED invoice exist for this request?"
CREATE INDEX ix_invoice_request_status ON invoice (service_request_id, status);
CREATE INDEX ix_invoice_vessel_status  ON invoice (vessel_id, status);
CREATE INDEX ix_invoice_org_status     ON invoice (organization_id, status);
