-- =====================================================================
--  fleet: documents and certificates (SoW s7, s9.3)
--
--  "Documents and certificates attached to a Spare, with issue and expiry
--  dates, and reminders before they expire." A document belongs to one vessel,
--  which is the scope column every guard keys on; the owner tells you what on
--  that vessel it is attached to.
--
--  Files live outside the database (seastella.upload.storage-dir); this table
--  holds the record: who uploaded it, its checksum, its dates, and - for a
--  replaced document - which version replaced it, so history is kept rather
--  than overwritten (DOC-06).
-- =====================================================================

CREATE TABLE document (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT       NOT NULL,
    vessel_id            BIGINT       NOT NULL,
    owner_type           VARCHAR(24)  NOT NULL,
    owner_id             BIGINT       NOT NULL,
    document_type        VARCHAR(24)  NOT NULL,
    title                VARCHAR(200) NOT NULL,
    -- Certificates only: what it is, who issued it, and when it runs out.
    certificate_number   VARCHAR(80),
    issuing_authority    VARCHAR(160),
    issued_date          DATE,
    expiry_date          DATE,
    file_name            VARCHAR(255) NOT NULL,
    content_type         VARCHAR(120) NOT NULL,
    size_bytes           BIGINT       NOT NULL,
    -- Opaque name on disk: never the uploaded name, so nothing is written to a
    -- path a caller chose, and nothing is served as executable (SEC-16).
    storage_key          VARCHAR(80)  NOT NULL,
    sha256               VARCHAR(64)  NOT NULL,
    uploaded_by_user_id  BIGINT       NOT NULL,
    uploaded_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    superseded_by_id     BIGINT,
    removed_at           TIMESTAMP WITH TIME ZONE,
    removed_by_user_id   BIGINT,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by           VARCHAR(160),
    updated_at           TIMESTAMP WITH TIME ZONE,
    updated_by           VARCHAR(160),
    version              BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uk_document_storage_key UNIQUE (storage_key),
    CONSTRAINT fk_document_vessel_org  FOREIGN KEY (vessel_id, organization_id)
        REFERENCES vessel (id, organization_id),
    CONSTRAINT fk_document_uploader    FOREIGN KEY (uploaded_by_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_document_remover     FOREIGN KEY (removed_by_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_document_superseded  FOREIGN KEY (superseded_by_id) REFERENCES document (id),
    CONSTRAINT ck_document_owner CHECK (owner_type IN ('VESSEL', 'SPARE', 'SERVICE_REQUEST')),
    CONSTRAINT ck_document_type CHECK (
        document_type IN ('CERTIFICATE', 'MANUAL', 'PHOTO', 'REPORT', 'OTHER')),
    -- A certificate is the one kind that must say when it expires (DOC-02).
    CONSTRAINT ck_document_certificate CHECK (
        document_type <> 'CERTIFICATE' OR expiry_date IS NOT NULL)
);

CREATE INDEX ix_document_owner  ON document (owner_type, owner_id, id);
CREATE INDEX ix_document_vessel ON document (vessel_id, document_type);
-- The daily expiry scan reads exactly this.
CREATE INDEX ix_document_expiry ON document (expiry_date, removed_at);
