-- =====================================================================
--  fleet: the service history of a Spare (SoW s6.3, s9.3)
--
--  "Every request - whether closed without cost in Phase B or completed by a
--  Service Engineer visit - remains permanently attached to that Spare's
--  service history, maintained centrally by Seastella."
--
--  Until now that history was one column, last_annual_service_date: the date
--  of the most recent service and nothing else. That is enough to drive the
--  maintenance engine and not enough to answer the question an auditor or a
--  new client actually asks - what has been done to this item, when, and by
--  whom. A fleet joining the platform also arrives with years of history that
--  predates it, and had nowhere to put it.
--
--  Two sources, one table:
--    PLATFORM  - written by the platform when a service request completes;
--                carries the request number and cannot be edited by hand.
--    RECORDED  - entered by the Technical Head, typically back-dated, for work
--                done before the platform or by someone outside it.
--
--  The distinction is kept because it is the first thing anyone reviewing the
--  history will want to know: did the system observe this, or was it typed in?
-- =====================================================================

CREATE TABLE spare_service_record (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spare_id            BIGINT       NOT NULL,
    -- Denormalised on purpose: every scoped read filters by vessel, and the
    -- alternative is a join to spare on a table that is read constantly.
    vessel_id           BIGINT       NOT NULL,
    service_date        DATE         NOT NULL,
    source              VARCHAR(16)  NOT NULL,
    -- What was done. For a completed request this is the engineer's summary.
    work_performed      VARCHAR(2000) NOT NULL,
    parts_used          VARCHAR(1000),
    -- Free text: before the platform, the servicer was often a third party
    -- who has no account here and never will.
    performed_by        VARCHAR(200),
    -- Set for PLATFORM records; null for anything entered by hand.
    service_request_id  BIGINT,
    request_number      VARCHAR(60),
    -- Who typed it in, for a RECORDED row. Null for PLATFORM rows, where the
    -- request itself carries the actor.
    recorded_by_user_id BIGINT,
    notes               VARCHAR(1000),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by          VARCHAR(160),
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          VARCHAR(160),
    version             BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_service_record_spare    FOREIGN KEY (spare_id) REFERENCES spare (id),
    CONSTRAINT fk_service_record_vessel   FOREIGN KEY (vessel_id) REFERENCES vessel (id),
    CONSTRAINT fk_service_record_recorder FOREIGN KEY (recorded_by_user_id) REFERENCES app_user (id),
    CONSTRAINT ck_service_record_source   CHECK (source IN ('PLATFORM', 'RECORDED')),
    -- A platform record is only ever written from a request; a recorded one is
    -- only ever written by a person. Neither can masquerade as the other.
    CONSTRAINT ck_service_record_origin   CHECK (
        (source = 'PLATFORM' AND service_request_id IS NOT NULL AND recorded_by_user_id IS NULL)
        OR (source = 'RECORDED' AND service_request_id IS NULL AND recorded_by_user_id IS NOT NULL)),
    -- One completed request produces one history row, however many times the
    -- completion is replayed.
    CONSTRAINT uk_service_record_request  UNIQUE (service_request_id)
);

-- The history of one item, newest first: the only read that matters.
CREATE INDEX ix_service_record_spare  ON spare_service_record (spare_id, service_date DESC);
-- "What was serviced across this fleet last year", for reports and the audit.
CREATE INDEX ix_service_record_vessel ON spare_service_record (vessel_id, service_date DESC);

-- Carry across what the single column already knew, so no vessel appears to
-- have lost its history the moment this table arrives. Marked RECORDED
-- because the platform did not observe it: it was imported or typed in.
INSERT INTO spare_service_record
    (spare_id, vessel_id, service_date, source, work_performed, performed_by,
     recorded_by_user_id, notes, created_at)
SELECT s.id, s.vessel_id, s.last_annual_service_date, 'RECORDED',
       'Annual service', NULL,
       (SELECT u.id FROM app_user u WHERE u.role = 'PLATFORM_ADMIN' ORDER BY u.id LIMIT 1),
       'Carried over from the spare record when service history was introduced.',
       CURRENT_TIMESTAMP
FROM spare s
WHERE s.last_annual_service_date IS NOT NULL
  AND EXISTS (SELECT 1 FROM app_user u WHERE u.role = 'PLATFORM_ADMIN');
