-- =====================================================================
--  fleet: organization, vessel, equipment category, the Spare tree, parts
-- =====================================================================

CREATE TABLE organization (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(160) NOT NULL,
    code          VARCHAR(24)  NOT NULL,
    address       VARCHAR(400),
    contact_email VARCHAR(254),
    contact_phone VARCHAR(40),
    status        VARCHAR(16)  NOT NULL,
    seed_marker   VARCHAR(8),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(160),
    updated_at    TIMESTAMP WITH TIME ZONE,
    updated_by    VARCHAR(160),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_organization_code UNIQUE (code)
);

CREATE TABLE vessel (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL,
    name            VARCHAR(120) NOT NULL,
    imo_number      VARCHAR(10)  NOT NULL,
    mmsi            VARCHAR(12),
    call_sign       VARCHAR(16),
    flag            VARCHAR(64),
    vessel_class    VARCHAR(64),
    area            VARCHAR(64),
    vessel_type     VARCHAR(64),
    dwt             NUMERIC(12,2),
    status          VARCHAR(24)  NOT NULL,
    seed_marker     VARCHAR(8),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by      VARCHAR(160),
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      VARCHAR(160),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_vessel_imo UNIQUE (imo_number),
    CONSTRAINT fk_vessel_organization FOREIGN KEY (organization_id) REFERENCES organization (id),
    -- Needed so child tables can carry a composite FK that pins them to the
    -- same vessel; see the note on spare below.
    CONSTRAINT uk_vessel_id_org UNIQUE (id, organization_id)
);

CREATE INDEX ix_vessel_org_status ON vessel (organization_id, status);

-- A LOOKUP, not an asset (SoW s9.2). No serial number, no running hours, no
-- service history, and deliberately no vessel_id: categories are global.
CREATE TABLE equipment_category (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(40) NOT NULL,
    name          VARCHAR(80) NOT NULL,
    display_order INTEGER     NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(160),
    updated_at    TIMESTAMP WITH TIME ZONE,
    updated_by    VARCHAR(160),
    version       BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uk_equipment_category_code UNIQUE (code)
);

-- THE SERVICEABLE ASSET (SoW s9). Recursive: a spare may parent further spares,
-- mirroring the VMP decimal ids (13 Radar -> 13.1 X-Band -> 13.1.2 Display Fan).
CREATE TABLE spare (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vessel_id                BIGINT       NOT NULL,
    equipment_category_id    BIGINT       NOT NULL,
    parent_spare_id          BIGINT,
    path                     VARCHAR(255) NOT NULL,
    depth                    SMALLINT     NOT NULL,
    vmp_ref                  VARCHAR(32),
    name                     VARCHAR(200) NOT NULL,
    make                     VARCHAR(120),
    model                    VARCHAR(120),
    serial_number            VARCHAR(120),
    software_version         VARCHAR(64),
    installation_date        DATE,
    expiration_date          DATE,
    last_annual_service_date DATE,
    last_survey_date         DATE,
    last_apt_date            DATE,
    running_hours            NUMERIC(12,2),
    tracks_running_hours     BOOLEAN      NOT NULL DEFAULT FALSE,
    criticality              VARCHAR(16)  NOT NULL,
    status                   VARCHAR(24)  NOT NULL,
    seed_marker              VARCHAR(8),
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by               VARCHAR(160),
    updated_at               TIMESTAMP WITH TIME ZONE,
    updated_by               VARCHAR(160),
    version                  BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_spare_vessel   FOREIGN KEY (vessel_id) REFERENCES vessel (id),
    CONSTRAINT fk_spare_category FOREIGN KEY (equipment_category_id) REFERENCES equipment_category (id),

    CONSTRAINT uk_spare_vessel_path   UNIQUE (vessel_id, path),
    CONSTRAINT uk_spare_vessel_vmpref UNIQUE (vessel_id, vmp_ref),

    -- Composite key so children can be pinned to the same vessel as the parent.
    CONSTRAINT uk_spare_id_vessel UNIQUE (id, vessel_id),

    CONSTRAINT ck_spare_not_own_parent CHECK (parent_spare_id IS NULL OR parent_spare_id <> id),
    CONSTRAINT ck_spare_depth CHECK (depth >= 0)
);

-- A SPARE TREE CAN NEVER SPAN TWO VESSELS.
--
-- Expressed as a composite foreign key rather than a trigger: (parent_spare_id,
-- vessel_id) must match an existing (id, vessel_id) pair, so a parent on a
-- different vessel simply has no matching row. This is portable across
-- PostgreSQL and H2, needs no procedural code, and cannot be bypassed by a
-- direct SQL write - which matters, because a cross-vessel child would be a
-- silent route around vessel isolation.
ALTER TABLE spare ADD CONSTRAINT fk_spare_parent_same_vessel
    FOREIGN KEY (parent_spare_id, vessel_id) REFERENCES spare (id, vessel_id);

CREATE INDEX ix_spare_vessel_category ON spare (vessel_id, equipment_category_id);
CREATE INDEX ix_spare_vessel_path     ON spare (vessel_id, path);
CREATE INDEX ix_spare_parent          ON spare (parent_spare_id);
CREATE INDEX ix_spare_vessel_crit     ON spare (vessel_id, criticality);

-- Consumable stock held for swapping into a spare. NOT the spare itself
-- (SoW s7). Quantity and minimum live here and nowhere else.
CREATE TABLE replacement_part (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vessel_id        BIGINT       NOT NULL,
    spare_id         BIGINT,
    name             VARCHAR(200) NOT NULL,
    part_number      VARCHAR(120),
    manufacturer     VARCHAR(120),
    quantity_on_hand INTEGER      NOT NULL DEFAULT 0,
    minimum_quantity INTEGER      NOT NULL DEFAULT 0,
    location         VARCHAR(120),
    expiry_date      DATE,
    seed_marker      VARCHAR(8),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by       VARCHAR(160),
    updated_at       TIMESTAMP WITH TIME ZONE,
    updated_by       VARCHAR(160),
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT fk_part_vessel FOREIGN KEY (vessel_id) REFERENCES vessel (id),
    CONSTRAINT fk_part_spare  FOREIGN KEY (spare_id, vessel_id) REFERENCES spare (id, vessel_id),
    CONSTRAINT ck_part_quantities CHECK (quantity_on_hand >= 0 AND minimum_quantity >= 0)
);

CREATE INDEX ix_part_vessel ON replacement_part (vessel_id);
