-- =====================================================================
--  fleet: the latest software version each equipment model should be running
--
--  A vessel's equipment already records the software version installed on it
--  (spare.software_version). On its own that number answers nothing: 5.5 is
--  only interesting once you know the manufacturer has shipped 5.6. Today the
--  superintendent carries that second number in their head, and an out-of-date
--  ECDIS is found at an inspection rather than from the fleet list.
--
--  This table is the other half - the client's master sheet, one row per
--  equipment model, naming the version that model ought to be on. The fleet
--  list then compares the two and says CURRENT or OUTDATED, the same way the
--  maintenance engine decides a due status: on the server, once, so every
--  screen and report gives the same answer.
--
--  Identity is make + model, not the equipment name. "AIS" is a category and
--  carries no software; "Furuno FA-170" is a device with a release history.
--  Both are folded to lower case and stripped of the punctuation people vary
--  on, so the sheet's "FA-170" matches a vessel's "FA170" instead of quietly
--  matching nothing - a silent miss here reads as "no baseline recorded",
--  which is exactly the state this table exists to end.
--
--  equipment_name is carried for display only: it is what the client's sheet
--  called the row, and showing it back is how they recognise their own data.
-- =====================================================================

CREATE TABLE software_baseline (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- As the sheet spells them, for display and for re-export.
    make             VARCHAR(120) NOT NULL,
    model            VARCHAR(120) NOT NULL,
    -- The match key: make and model folded and stripped. Stored rather than
    -- computed so the unique constraint below is enforceable on H2 and
    -- PostgreSQL alike, and so a lookup is an index hit, not a table scan.
    match_key        VARCHAR(260) NOT NULL,
    -- What the sheet's row was called, e.g. "AIS". Display only; never matched
    -- on, because a category name is not a device.
    equipment_name   VARCHAR(200),
    latest_version   VARCHAR(64)  NOT NULL,
    -- Where this row came from, so a hand correction is distinguishable from
    -- the last sheet upload and survives the next one being reviewed.
    source           VARCHAR(16)  NOT NULL,
    notes            VARCHAR(500),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by       VARCHAR(160),
    updated_at       TIMESTAMP WITH TIME ZONE,
    updated_by       VARCHAR(160),
    version          BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT ck_software_baseline_source CHECK (source IN ('IMPORTED', 'RECORDED')),
    -- One model, one baseline. A re-upload updates the row it matches rather
    -- than laying a second answer beside the first.
    CONSTRAINT uk_software_baseline_key    UNIQUE (match_key)
);

-- The whole table is read at once to decorate a vessel's fit, and it is small
-- (hundreds of rows). The unique index above already serves the point lookup.
