-- =====================================================================
--  fleet: running-hour readings
--
--  SoW s7: "Monthly running-hour capture per Spare, historical readings
--  retained." Append-only - a reading is never edited or deleted, so the
--  history behind every running-hour due date stays traceable (SOURCE-B s11).
-- =====================================================================

CREATE TABLE running_hour_reading (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spare_id               BIGINT        NOT NULL,
    vessel_id              BIGINT        NOT NULL,
    reading_hours          NUMERIC(12,2) NOT NULL,
    previous_reading_hours NUMERIC(12,2),
    reading_date           DATE          NOT NULL,
    recorded_by_user_id    BIGINT        NOT NULL,
    note                   VARCHAR(500),
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by             VARCHAR(160),
    updated_at             TIMESTAMP WITH TIME ZONE,
    updated_by             VARCHAR(160),
    version                BIGINT        NOT NULL DEFAULT 0,

    -- Composite FK pins the reading to the spare's own vessel.
    CONSTRAINT fk_rhr_spare    FOREIGN KEY (spare_id, vessel_id) REFERENCES spare (id, vessel_id),
    CONSTRAINT fk_rhr_recorder FOREIGN KEY (recorded_by_user_id) REFERENCES app_user (id),
    CONSTRAINT ck_rhr_hours    CHECK (reading_hours >= 0)
);

CREATE INDEX ix_rhr_spare_date ON running_hour_reading (spare_id, reading_date, id);
