-- =====================================================================
--  platform-core: audit trail
--
--  Migration order note: files are versioned by DATABASE dependency, not by
--  Maven dependency. fleet (V2) creates organization/vessel before
--  identity-access (V3) adds foreign keys to them, even though Maven has
--  fleet depending on identity-access.
-- =====================================================================

-- Append-only. No updated_at, no version column: an audit row is written once.
-- Database-level protection (revoking UPDATE/DELETE) is applied per-vendor in
-- the postgresql migration; application-level protection is the absence of any
-- setter on AuditEntry.
CREATE TABLE audit_entry (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id   BIGINT,
    actor_role      VARCHAR(32),
    action          VARCHAR(80)  NOT NULL,
    entity_type     VARCHAR(80)  NOT NULL,
    entity_id       BIGINT,
    organization_id BIGINT,
    vessel_id       BIGINT,
    before_value    TEXT,
    after_value     TEXT,
    ip_address      VARCHAR(45),
    user_agent      VARCHAR(255),
    occurred_at     TIMESTAMP WITH TIME ZONE NOT NULL
);

-- The audit report reads newest-first, and drills down by entity or by org.
CREATE INDEX ix_audit_occurred        ON audit_entry (occurred_at DESC);
CREATE INDEX ix_audit_entity          ON audit_entry (entity_type, entity_id);
CREATE INDEX ix_audit_org_occurred    ON audit_entry (organization_id, occurred_at DESC);
CREATE INDEX ix_audit_actor           ON audit_entry (actor_user_id, occurred_at DESC);
