-- =====================================================================
--  troubleshooting: the Automated Troubleshooting Assistant (SoW s6.1)
--
--  A rule engine, not a chatbot (s13, s15): guided checks authored as data,
--  keyed on equipment category x problem type, so Seastella can add checks
--  without a release. Every question asked and every answer given is kept
--  against the request, whether or not it resolved anything (s6.1).
-- =====================================================================

CREATE TABLE troubleshooting_flow (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Both nullable: a flow for a category with no problem type applies to any
    -- problem on that equipment; one with neither is the general fallback.
    equipment_category_id BIGINT,
    problem_type_id       BIGINT,
    code                  VARCHAR(60)  NOT NULL,
    name                  VARCHAR(160) NOT NULL,
    flow_version          INTEGER      NOT NULL,
    published             BOOLEAN      NOT NULL,
    -- SAMPLE until Seastella supplies approved content (s16, OI-05).
    content_source        VARCHAR(16)  NOT NULL,
    start_step_key        VARCHAR(40)  NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by            VARCHAR(160),
    updated_at            TIMESTAMP WITH TIME ZONE,
    updated_by            VARCHAR(160),
    version               BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uk_ts_flow_code_version UNIQUE (code, flow_version),
    CONSTRAINT fk_ts_flow_category FOREIGN KEY (equipment_category_id) REFERENCES equipment_category (id),
    CONSTRAINT fk_ts_flow_problem  FOREIGN KEY (problem_type_id) REFERENCES problem_type (id),
    CONSTRAINT ck_ts_flow_source   CHECK (content_source IN ('SAMPLE', 'SEASTELLA'))
);

CREATE INDEX ix_ts_flow_selection ON troubleshooting_flow (equipment_category_id, problem_type_id, published);

-- One yes/no check. Each answer leads to another step or ends in an outcome,
-- never both and never neither.
CREATE TABLE troubleshooting_step (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flow_id       BIGINT        NOT NULL,
    step_key      VARCHAR(40)   NOT NULL,
    display_order INTEGER       NOT NULL,
    prompt        VARCHAR(500)  NOT NULL,
    help_text     VARCHAR(1000),
    input_kind    VARCHAR(16)   NOT NULL,
    yes_next_key  VARCHAR(40),
    yes_outcome   VARCHAR(16),
    no_next_key   VARCHAR(40),
    no_outcome    VARCHAR(16),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(160),
    updated_at    TIMESTAMP WITH TIME ZONE,
    updated_by    VARCHAR(160),
    version       BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT uk_ts_step_key  UNIQUE (flow_id, step_key),
    CONSTRAINT fk_ts_step_flow FOREIGN KEY (flow_id) REFERENCES troubleshooting_flow (id),
    CONSTRAINT ck_ts_step_kind CHECK (input_kind IN ('YES_NO')),
    CONSTRAINT ck_ts_step_yes  CHECK ((yes_next_key IS NULL AND yes_outcome IS NOT NULL)
                                     OR (yes_next_key IS NOT NULL AND yes_outcome IS NULL)),
    CONSTRAINT ck_ts_step_no   CHECK ((no_next_key IS NULL AND no_outcome IS NOT NULL)
                                     OR (no_next_key IS NOT NULL AND no_outcome IS NULL)),
    CONSTRAINT ck_ts_step_outcomes CHECK (
        (yes_outcome IS NULL OR yes_outcome IN ('RESOLVED', 'TEMPORARY_FIX', 'UNRESOLVED'))
        AND (no_outcome IS NULL OR no_outcome IN ('RESOLVED', 'TEMPORARY_FIX', 'UNRESOLVED')))
);

-- One run of the checks per request. It records the flow version it ran, so a
-- later edit to the content never rewrites what the Captain was asked.
CREATE TABLE troubleshooting_session (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id BIGINT       NOT NULL,
    vessel_id          BIGINT       NOT NULL,
    flow_id            BIGINT       NOT NULL,
    flow_version       INTEGER      NOT NULL,
    status             VARCHAR(16)  NOT NULL,
    current_step_id    BIGINT,
    outcome            VARCHAR(16),
    root_cause_note    VARCHAR(1000),
    temporary_fix_note VARCHAR(1000),
    started_by_user_id BIGINT       NOT NULL,
    started_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at       TIMESTAMP WITH TIME ZONE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by         VARCHAR(160),
    updated_at         TIMESTAMP WITH TIME ZONE,
    updated_by         VARCHAR(160),
    version            BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uk_ts_session_request UNIQUE (service_request_id),
    CONSTRAINT fk_ts_session_request FOREIGN KEY (service_request_id) REFERENCES service_request (id),
    CONSTRAINT fk_ts_session_flow    FOREIGN KEY (flow_id) REFERENCES troubleshooting_flow (id),
    CONSTRAINT fk_ts_session_step    FOREIGN KEY (current_step_id) REFERENCES troubleshooting_step (id),
    CONSTRAINT fk_ts_session_starter FOREIGN KEY (started_by_user_id) REFERENCES app_user (id),
    CONSTRAINT ck_ts_session_status  CHECK (status IN ('IN_PROGRESS', 'OUTCOME_REACHED', 'COMPLETED')),
    CONSTRAINT ck_ts_session_outcome CHECK (outcome IS NULL OR outcome IN ('RESOLVED', 'TEMPORARY_FIX', 'UNRESOLVED'))
);

CREATE INDEX ix_ts_session_vessel ON troubleshooting_session (vessel_id);

-- Every question as it was asked, and the answer given. Append-only.
CREATE TABLE troubleshooting_response (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id          BIGINT       NOT NULL,
    step_id             BIGINT       NOT NULL,
    prompt              VARCHAR(500) NOT NULL,
    response_value      VARCHAR(16)  NOT NULL,
    note                VARCHAR(500),
    answered_by_user_id BIGINT       NOT NULL,
    answered_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by          VARCHAR(160),
    updated_at          TIMESTAMP WITH TIME ZONE,
    updated_by          VARCHAR(160),
    version             BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_ts_response_session FOREIGN KEY (session_id) REFERENCES troubleshooting_session (id),
    CONSTRAINT fk_ts_response_step    FOREIGN KEY (step_id) REFERENCES troubleshooting_step (id),
    CONSTRAINT fk_ts_response_user    FOREIGN KEY (answered_by_user_id) REFERENCES app_user (id),
    CONSTRAINT ck_ts_response_value   CHECK (response_value IN ('YES', 'NO'))
);

CREATE INDEX ix_ts_response_session ON troubleshooting_response (session_id, id);
