-- =====================================================================
--  troubleshooting: Live Agent Chat (SoW s6.1, s7)
--
--  "If the guided checks don't resolve it, the Captain can escalate the same
--  request to a Live Agent Chat - a real-time conversation with the Seastella
--  Service Coordinator ... Every question, check and message across both the
--  automated session and the live chat is logged against the request."
--
--  One conversation per request, never a separate chat store: the transcript
--  is part of the service record (master brief s10). Human-to-human only.
-- =====================================================================

CREATE TABLE conversation (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_request_id BIGINT      NOT NULL,
    vessel_id          BIGINT      NOT NULL,
    status             VARCHAR(16) NOT NULL,
    escalated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at          TIMESTAMP WITH TIME ZONE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by         VARCHAR(160),
    updated_at         TIMESTAMP WITH TIME ZONE,
    updated_by         VARCHAR(160),
    version            BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT uk_conversation_request UNIQUE (service_request_id),
    CONSTRAINT fk_conversation_request FOREIGN KEY (service_request_id) REFERENCES service_request (id),
    CONSTRAINT ck_conversation_status  CHECK (status IN ('LIVE', 'CLOSED'))
);

-- Append-only transcript. client_msg_id makes a retried send idempotent.
CREATE TABLE conversation_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT        NOT NULL,
    sender_kind     VARCHAR(16)   NOT NULL,
    sender_user_id  BIGINT,
    sender_role     VARCHAR(32),
    body            VARCHAR(2000) NOT NULL,
    client_msg_id   VARCHAR(64),
    sent_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by      VARCHAR(160),
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      VARCHAR(160),
    version         BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT uk_message_client_id   UNIQUE (conversation_id, client_msg_id),
    CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversation (id),
    CONSTRAINT fk_message_sender      FOREIGN KEY (sender_user_id) REFERENCES app_user (id),
    CONSTRAINT ck_message_kind        CHECK (sender_kind IN ('USER', 'SYSTEM')),
    CONSTRAINT ck_message_sender      CHECK ((sender_kind = 'USER' AND sender_user_id IS NOT NULL)
                                             OR (sender_kind = 'SYSTEM' AND sender_user_id IS NULL))
);

CREATE INDEX ix_message_conversation ON conversation_message (conversation_id, id);
