-- =====================================================================
--  troubleshooting: one thread, read state and attachments (CHT-04, CHT-07,
--  CHT-08, CHT-10)
--
--  Master brief s10 asks that assistant, human and system messages share one
--  conversation, that a conversation have a status (assistant / live / closed),
--  that read state be kept, and that messages carry attachments.
--
--  The conversation therefore no longer begins at escalation: it begins when
--  the guided checks start, in ASSISTANT status, and escalation moves it to
--  LIVE. The old escalated_at column becomes opened_at (which is what it
--  recorded), and escalated_at is re-added as the moment a live agent was
--  asked for - null for a conversation that never needed one.
-- =====================================================================

ALTER TABLE conversation RENAME COLUMN escalated_at TO opened_at;
ALTER TABLE conversation ADD COLUMN escalated_at TIMESTAMP WITH TIME ZONE;

-- Every conversation that exists today was opened by an escalation.
UPDATE conversation SET escalated_at = opened_at;

ALTER TABLE conversation DROP CONSTRAINT ck_conversation_status;
ALTER TABLE conversation ADD CONSTRAINT ck_conversation_status
    CHECK (status IN ('ASSISTANT', 'LIVE', 'CLOSED'));
-- A conversation is LIVE only because someone asked for a live agent.
ALTER TABLE conversation ADD CONSTRAINT ck_conversation_escalated
    CHECK (status <> 'LIVE' OR escalated_at IS NOT NULL);

-- The assistant writes in the same transcript as the people (CHT-04).
ALTER TABLE conversation_message DROP CONSTRAINT ck_message_kind;
ALTER TABLE conversation_message DROP CONSTRAINT ck_message_sender;
ALTER TABLE conversation_message ADD CONSTRAINT ck_message_kind
    CHECK (sender_kind IN ('USER', 'SYSTEM', 'ASSISTANT'));
ALTER TABLE conversation_message ADD CONSTRAINT ck_message_sender
    CHECK ((sender_kind = 'USER' AND sender_user_id IS NOT NULL)
           OR (sender_kind <> 'USER' AND sender_user_id IS NULL));

-- An attachment is a document like any other: same storage, same byte check,
-- same scope rules. The message only points at it (CHT-08).
ALTER TABLE conversation_message ADD COLUMN document_id BIGINT;
ALTER TABLE conversation_message ADD CONSTRAINT fk_message_document
    FOREIGN KEY (document_id) REFERENCES document (id);

-- How far each person has read (CHT-07). One row per person per conversation;
-- the id, not a timestamp, so it cannot disagree with the transcript order.
CREATE TABLE conversation_read (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id      BIGINT NOT NULL,
    user_id              BIGINT NOT NULL,
    last_read_message_id BIGINT NOT NULL,
    read_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by           VARCHAR(160),
    updated_at           TIMESTAMP WITH TIME ZONE,
    updated_by           VARCHAR(160),
    version              BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT uk_conversation_read UNIQUE (conversation_id, user_id),
    CONSTRAINT fk_read_conversation FOREIGN KEY (conversation_id) REFERENCES conversation (id),
    CONSTRAINT fk_read_user         FOREIGN KEY (user_id) REFERENCES app_user (id)
);

CREATE INDEX ix_conversation_read_user ON conversation_read (user_id, conversation_id);
