-- =====================================================================
--  maintenance: last observed colour status per spare
--
--  SoW s11: "Maintenance approaching / due / overdue (colour-status change)
--  - notifies Captain, Ship Manager and Technical Head". An alert is raised on
--  a CHANGE, so the engine has to remember what it last saw. Status is still
--  derived on read everywhere else; this row exists only to detect the change.
-- =====================================================================

CREATE TABLE spare_due_state (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spare_id      BIGINT      NOT NULL,
    vessel_id     BIGINT      NOT NULL,
    status        VARCHAR(24) NOT NULL,
    next_due_date DATE,
    basis         VARCHAR(24),
    evaluated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(160),
    updated_at    TIMESTAMP WITH TIME ZONE,
    updated_by    VARCHAR(160),
    version       BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT uk_due_state_spare UNIQUE (spare_id),
    CONSTRAINT fk_due_state_spare FOREIGN KEY (spare_id, vessel_id) REFERENCES spare (id, vessel_id),
    CONSTRAINT ck_due_state_status CHECK (
        status IN ('NORMAL', 'APPROACHING', 'URGENT', 'DUE', 'OVERDUE', 'NOT_TRACKED')
    )
);

CREATE INDEX ix_due_state_vessel ON spare_due_state (vessel_id);
