-- =====================================================================
--  maintenance: configurable colour thresholds, per-spare rules
-- =====================================================================

-- Thresholds are ROWS, not constants (reference spec s14 requires them to be
-- administrable). organization_id NULL means the platform default.
CREATE TABLE maintenance_threshold (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    status_code     VARCHAR(24) NOT NULL,
    min_days        INTEGER,
    max_days        INTEGER,
    active          BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by      VARCHAR(160),
    updated_at      TIMESTAMP WITH TIME ZONE,
    updated_by      VARCHAR(160),
    version         BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT fk_threshold_organization FOREIGN KEY (organization_id) REFERENCES organization (id),
    CONSTRAINT ck_threshold_status CHECK (
        status_code IN ('NORMAL', 'APPROACHING', 'URGENT', 'DUE', 'OVERDUE')
    ),
    CONSTRAINT ck_threshold_range CHECK (min_days IS NULL OR max_days IS NULL OR min_days <= max_days)
);

CREATE INDEX ix_threshold_org ON maintenance_threshold (organization_id, active);

CREATE TABLE spare_maintenance_rule (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spare_id           BIGINT      NOT NULL,
    vessel_id          BIGINT      NOT NULL,
    rule_type          VARCHAR(24) NOT NULL,
    interval_days      INTEGER,
    interval_hours     NUMERIC(12,2),
    last_service_date  DATE,
    last_service_hours NUMERIC(12,2),
    next_due_date      DATE,
    next_due_hours     NUMERIC(12,2),
    active             BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by         VARCHAR(160),
    updated_at         TIMESTAMP WITH TIME ZONE,
    updated_by         VARCHAR(160),
    version            BIGINT      NOT NULL DEFAULT 0,

    -- Composite FK pins the rule to the spare's own vessel.
    CONSTRAINT fk_rule_spare FOREIGN KEY (spare_id, vessel_id) REFERENCES spare (id, vessel_id),
    CONSTRAINT ck_rule_type CHECK (rule_type IN ('CALENDAR', 'RUNNING_HOURS')),
    CONSTRAINT ck_rule_interval CHECK (
        (rule_type = 'CALENDAR' AND interval_days IS NOT NULL)
        OR (rule_type = 'RUNNING_HOURS' AND interval_hours IS NOT NULL)
    )
);

-- Every "due soon / overdue" dashboard count reads next_due_date for a set of
-- vessels, so this is the index that keeps those aggregates cheap.
CREATE INDEX ix_rule_vessel_due ON spare_maintenance_rule (vessel_id, active, next_due_date);
CREATE INDEX ix_rule_spare      ON spare_maintenance_rule (spare_id, active);
CREATE INDEX ix_rule_due_date   ON spare_maintenance_rule (next_due_date);
